/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "main.h"
#include "projectconf.h"
#include "systemfunctions.h"
#include "ports.h"

#include "uart.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{

	uint32_t delayTimeStamp = Get_SystemTimeMs();

	char *dataBuffTx = "Write something:\n\r";
	char dataBuffRx[100] = {0};

	// System configurations
	System_Config();

	// Uart configuration
	uart_Init();

	// Start in new line

	uart_SingleByte_Tx('\n');
	uart_SingleByte_Tx('\r');

	while(1)
	{

		if(Compare_SystemTimeMs(delayTimeStamp) > 5000)
		{

			// Write something

			uart_MultiByte_Tx((uint8_t *)dataBuffTx, 18);

			// Wait a response

			int i = 0;
			uint8_t c = 0;

			do
			{

				// Read byte by byte what the user write

				uart_SingleByte_Rx(&c);

				dataBuffRx[i] = c;

				// Echo byte by byte back

				uart_SingleByte_Tx((uint8_t)c);

				// Increment index

				i++;

				if(i >= 100)
					i = 0;

			}while(c != '\r'); // Check for the end


			// Send a new line character

			uart_SingleByte_Tx('\n');
			uart_SingleByte_Tx('\r');

			// Wait 5 seconds

			delayTimeStamp = Get_SystemTimeMs();

		}

	}

}



void SysTick_CallBack(void)
{

	SysTickCountMs++;

}

